### ISSUE TITLE
STYLE ISSUES: renew comments and reorder imports

### ISSUE THREAD

**Issue by Zheyuan-Robert-Xu** [anusii/podnotes#103]
# Description:
We should fix up all the STYLE issues in PODNOTES too from dart run dart_code_metrics:metrics analyze --disable-sunset-warning lib --reporter=console. There are many newline-before-return and prefer-trailing-comma fixes required which are simple to fix. Could you have a look at fixing them all please.

# Closing Criteria

- [x] Renew comments

- [x] Reorder imports

**Comment by Zheyuan-Robert-Xu** [comment]
Made pull request

**Comment by gjwgit** [comment]
No current issues.
