### ISSUE TITLE
Add note encryption/decryption functionality

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/podnotes#14]

**Comment by anushkavidanage** [comment]
Question: Do we need to encrypt all notes by default or do we give that option to the user?

**Comment by gjwgit** [comment]
It will be useful to have a checkbox that when checked the note is encrypted.

**Comment by gjwgit** [comment]
Let's simply always encrypt notes for now. This demonstrates the basic functionality. Have a separate task for optionally encrypt note, and tag as a good first task for someone.
