### ISSUE TITLE
MAC LOGIN: Connection failed (OS Error: Operation not permitted

### ISSUE THREAD

**Issue by jesscmoore** [anusii/podnotes#20]
Mac app is failing on press of Login button with

```
A Dart VM Service on macOS is available at: http://127.0.0.1:60898/E7g0qTKiXGM=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:60898/E7g0qTKiXGM=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = pods.solidcommunity.au, port = 443, uri=https://pods.solidcommunity.au/.well-known/openid-configuration
#0      IOClient.send (package:http/src/io_client.dart:119:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:solid_auth/src/openid/src/http_util.dart:56:12)
<asynchronous suspension>
#3      get (package:solid_auth/src/openid/src/http_util.dart:18:7)
<asynchronous suspension>
#4      Issuer.discover (package:solid_auth/src/openid/src/openid.dart:127:16)
<asynchronous suspension>
#5      authenticate (package:solid_auth/solid_auth_client.dart:118:19)
<asynchronous suspension>
#6      LoginScreen.createSolidLoginRow.<anonymous closure> (package:podnotes/login/screen.dart:193:19)
<asynchronous suspension>
```

**Comment by jesscmoore** [comment]
Anushka will ask Zheyuan about to investigate it.

**Comment by Zheyuan-Robert-Xu** [comment]
Update `macos/Runner/DebugProfile.entitlements` and  `macos/Runner/Release.entitlements`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
    <true/>
</dict>
</plist>
```
And need to Add team in the signing tab in Xcode
![Uploading Screenshot 2023-11-29 at 10.44.45 am.png…]()

**Comment by jesscmoore** [comment]
Thanks Zheyuan. Which team option should I choose?

**Comment by Zheyuan-Robert-Xu** [comment]
You need to sign an apple id account, and choose your own account. 
In the Singing tab of the picture, click the drop down icon of Team.

**Comment by jesscmoore** [comment]
@Zheyuan-Robert-Xu Issue resolved now. The trick was my code and macos had become incompatible, and these new versions of xcode require apple id signin even for development on local machine, allowing incoming + outgoing network connections. 
- Updated to Xcode v15.0.1
- Updated to MacOS Sonoma v14.1.2
- Switched to flutter channel beta

Configured xcode command line tools:
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch

Opened project in Xcode: macos/Runner.xcodeproj:
In Signing-in Capabilities:
Team: click Add and Signed in with apple id, selected my Team
Network: selected incoming and outgoing connections

Now able to build for macos, and login to solid pod

**Comment by jesscmoore** [comment]
Reverted back to `flutter channel stable` to see if flutter version mattered.
```
Flutter 3.16.3 • channel stable
```
With macos v14.1.2 and xcode 15.0.1 and xcode cli config as above, `flutter run -d macos` works, however there are many non-fatal errors
```
2023-12-09 22:51:42.972 xcodebuild[53512:315568] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x600000e28080>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
```
https://github.com/flutter/flutter/issues/139284

Changing back to beta, resolved the macos issue.
Flutter 3.18.0-0.1.pre • channel beta
