### ISSUE TITLE
NOTE: On SAVE NOTE can we stay with the current note rather then start a fresh note?

### ISSUE THREAD

**Issue by gjwgit** [anusii/podnotes#32]
# Description

After I click the `SAVE NOTE` button I seem to "lose" my note since the note is cleared and at first I am not quite sure what just happened 😊. Perhaps have a `SAVE NOTE` and a `NEW NOTE` button. `SAVE NOTE` simply updates the saving of the note (though I think that should just happen automatically these days - a topic for another issue).

# Why

So that the user workflow does not present surprises to the user.

# Closing Crieteria

- [x] `SAVE NOTE` does not clear the current note.

**Comment by jesscmoore** [comment]
Completed. Saves note and stays in note edit page

**Comment by gjwgit** [comment]
This works when editing an already saved note, but not a new note. Was that by design? I expected on SAVE NOTE that it stays with the current note, whether editing an existing note or for a new note.

**Comment by jesscmoore** [comment]
@graham I've altered home.dart also to stay on page after successful save.
PR https://github.com/anusii/podnotes/pull/94

**Comment by gjwgit** [comment]
Works nicely. Thanks @jesscmoore
