### ISSUE TITLE
ABOUT: Add an about popup

### ISSUE THREAD

**Issue by gjwgit** [anusii/podnotes#35]
# Description

Display an About text box that includes a simple description, lists the current version, a link to the github repository, and a list of the authors.

There is a standard About widget for flutter.

**Comment by jesscmoore** [comment]
Completed implementation of AboutDialog(). Uses application details including version set in constants/app.dart. Tried to get this from pubspec.yaml with package_info_plus, which would have been better. PR https://github.com/anusii/podnotes/pull/95

AboutDialog also creates a ViewLicenses popup - did you want that?

![Image](https://github.com/anusii/podnotes/assets/5244819/91347045-4f44-4b58-b4bf-a02ae3d91881)

View Licenses:

![Image](https://github.com/anusii/podnotes/assets/5244819/420049f4-1669-4b84-a205-8ec476c10115)

**Comment by gjwgit** [comment]
View Licenses is good. I'll work on getting version numbering working across the app. Would be good to source from pubspec (and keep sync with Makefile).

**Comment by gjwgit** [comment]
Closing. Version updated through makefile.
