### ISSUE TITLE
Create installers for the app

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/podnotes#63]
- [x] Android
- [x] Web
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by jesscmoore** [comment]
Macos installer build process documented here - https://github.com/anusii/podnotes/issues/75

**Comment by gjwgit** [comment]
Graham to do the Linux package.

**Comment by gjwgit** [comment]
Linux targz done.

**Comment by jesscmoore** [comment]
@gjwgit could you add the linux tarball to installers folder?

**Comment by gjwgit** [comment]
Ah - is that where it goes - I usually have a dist folder which is where I put it. I'll move it to installers. Are there scripts to create the others? Might be good to add them to the flutter.mk

**Comment by gjwgit** [comment]
- [ ] Task: Add Windows script to flutter chapter

**Comment by jesscmoore** [comment]
Thanks @gjwgit. I followed Anushka's lead of using installers folder, happy to go with dist folder.

I'll make a script for the mac build which packages to .dmg. This worked nicely on current macos sonoma

- [ ] make macos build script 
- [ ] share current macos method for flutter chapter
- [ ] add to README

**Comment by gjwgit** [comment]
Move macos script request to separate task. Closing this one now.
